# Generated by Django 5.0.6 on 2026-07-10 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bot_is_admin',
            field=models.BooleanField(default=False, help_text='Verified bot admin status via Telegram API'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='telegram_id',
            field=models.BigIntegerField(help_text='Telegram chat ID (e.g. -100123456789)', unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='@username without @', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chegirma foizi (0–100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Obuna muddati kunlarda', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(help_text="Masalan: '1 oylik', '3 oylik'", max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Narxi UZS da (minimum 100 so'm)", max_digits=12, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
