# Generated by Django 5.0.6 on 2026-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_user_id_78024b_idx',
            old_name='sub_user_channel_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_status_fc7385_idx',
            old_name='sub_status_enddate_idx',
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
