# Generated by Django 5.0.6 on 2026-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='expiring_days',
            field=models.PositiveIntegerField(blank=True, help_text="Agar target_type=expiring bo'lsa, necha kun ichida tugaydigan obunalar", null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
