# Generated by Django 5.0.6 on 2026-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='tx_payme_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_08c743_idx',
            old_name='tx_user_status_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payme_cancel_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payme_create_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payme_perform_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payme_state',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payme_transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text="Foydalanuvchi yuborgan to'lov cheki rasmi", null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(help_text='Miqdor tiyin da (1 UZS = 100 tiyin)'),
        ),
    ]
